# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f50fa2757166f2e136aed6b302f158b7a47a51e8c424611ba12e5a5411758b30a9d6fa2c051801589ec1a658a638ca92ff01f9b59f216a1feed1bf53537874b

test:
  secret_key_base: 4acfc1b6061667682a9bf8a122245980982a0957edc3980fbfbd1c3330bc07cfc3b0c108720491ff70a1a888d0c432fac90cb36cac28b7845583569a9b436c26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
